# Generated by Django 3.2.6 on 2021-08-19 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[0-9 ]*$', 'Only ten numbers allowed.')]),
        ),
    ]
