# Generated by Django 3.2.8 on 2021-11-27 20:28

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.JSONField(null=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator('\\d{3}?-?\\d{3}?-?\\d{4}', 'Only ten numbers and dashes allowed.')])),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=5)),
                ('zipcode', models.CharField(max_length=5, null=True)),
                ('subtotal', models.CharField(max_length=10, null=True)),
                ('tax', models.CharField(max_length=10, null=True)),
                ('total', models.CharField(max_length=10, null=True)),
                ('status', models.CharField(choices=[('PN', 'Pending'), ('RT', 'Return'), ('CM', 'Completed')], default='PN', max_length=2)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['status', 'created_at'],
            },
        ),
    ]
