# Generated by Django 3.2.8 on 2021-11-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='order',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax',
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.JSONField(encoder=list, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.JSONField(null=True),
        ),
    ]
