# Generated by Django 3.2.8 on 2021-11-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20211107_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.JSONField(null=True),
        ),
    ]
