# Generated by Django 3.2.3 on 2021-05-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qty',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
