# Generated by Django 3.2.3 on 2021-05-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='five',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='four',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='one',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='three',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='two',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
