# Generated by Django 3.2.6 on 2021-08-19 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210528_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['product']},
        ),
        migrations.AlterField(
            model_name='rating',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='store.product'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('product',)},
        ),
    ]
