# Generated by Django 3.2.8 on 2021-10-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210819_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='480px-No_image_available.png', upload_to='profile_pics'),
        ),
    ]
