# Generated by Django 3.2.8 on 2021-10-06 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='No_image_available.png', upload_to='profile_pics'),
        ),
    ]
